project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: "Hands-on Ex01"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on_Ex02(ggplot2)"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          
    
    - text: "In-class Exercise"
      menu:
      - text: "In-class_Ex01(Tableau)"
        href: "https://public.tableau.com/app/profile/huoda1027/viz/TakeHome_Ex01_16742612602400/Dashboard1"
      - text: "In-class_Ex03"
        href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
      - text: "In-class_Ex04"
        href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
      - text: "In-class_Ex05"
        href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
      - text: "In-class_Ex06"
        href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
      - text: "In-class_Ex07"
        href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
      - text: "In-class_Ex08"
        href: "In-class_Ex/In-class_Ex08/In-class_Ex08.html"
      - text: "In-class_Ex09"
        href: "In-class_Ex/In-class_Ex09/In-class_Ex09.html"
    
    - text: "Take-Home Exercise"
      menu:
      - text: "Take-Home_Ex01(Tableau)"
        href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
      - text: "Take-Home_Ex02(R):Age-sex Pyramids in Singapore"
        href: "Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html"
      - text: "Take-Home_Ex03(R): Time Series Analysis of Singapore Resale HDB price"
        href: "Take-Home_Ex/Take-Home_Ex03/Take-Home_Ex03.html"
      - text: "Take-Home_Ex04(R): Time Series Analysis of Singapore Trade"
        href: " " 
        
    
    
    
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

