---
title: "general case"
---

## Pros

+---------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Category      | Feature                        | Impact                                                                                                                                                                        |
+===============+================================+===============================================================================================================================================================================+
| Homepage      |                                |                                                                                                                                                                               |
+---------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|               | No Ads                         | Clean and nice layout improves the overall customer experience                                                                                                                |
|               |                                |                                                                                                                                                                               |
|               |                                | Customer's attention is not distracted                                                                                                                                        |
+---------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Food Delivery |                                |                                                                                                                                                                               |
+---------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|               | Pandabox                       | -   attract customers to make purchase with limited time of offers                                                                                                            |
|               |                                |                                                                                                                                                                               |
|               |                                | -   increase basket value                                                                                                                                                     |
|               |                                |                                                                                                                                                                               |
|               |                                | -   attract customers to try new restaurants                                                                                                                                  |
+---------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|               | Speed of Delivery              | shorter waiting time improves the overall customer experience                                                                                                                 |
+---------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|               | Professional Riders            | Riders will not leave food on the floor/hang it on the door handle when asked to leave the food at doorstep. Instead, they will place it on the empty space on the shoe rack. |
+---------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Pick-up       |                                |                                                                                                                                                                               |
+---------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|               | credit card promotion          | attract customers to link credit card                                                                                                                                         |
+---------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|               | pandapro enjoys extra discount | attract customers to subscribe, as pick up price sometimes cheaper than purchase in store                                                                                     |
+---------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Subsription   |                                |                                                                                                                                                                               |
+---------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|               | Lowest subscription fee        | Customers who is aware of the pick-up discount are more likely to join the membership                                                                                         |
+---------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Cons

+---------------+-------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| Category      | Feature                                                           | Impact                                                                                                                  |
+===============+===================================================================+=========================================================================================================================+
| Food Delivery |                                                                   |                                                                                                                         |
+---------------+-------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
|               | pandapro free delivery requirement not clearly stated             | customers might get disappointed                                                                                        |
+---------------+-------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
|               | choices on Chinese cuisines                                       | not as many as the competitor's                                                                                         |
+---------------+-------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
|               | no mix&match                                                      | customer choose not to place an order when they could not meet the minimum order amount from a single restaurant        |
+---------------+-------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
|               | no variation on delivery fee                                      | customers who are willing to wait for longer time to pay lower delivery fee might choose to order from competitor's app |
+---------------+-------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| Panda Rewards |                                                                   |                                                                                                                         |
+---------------+-------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
|               | the points could not be earned automatically after placing orders | customers who used to be awarded automatically might get disappointed                                                   |
+---------------+-------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+
